package database

// Reusable Terraform schema description fragments shared across the database
// service resources (mysql, mariadb, postgresql, epas, sqlserver, vertica,
// cachestore, searchengine, eventstreams). Centralized here to avoid
// duplicated string literals across the per-service cluster resources.
const (
	DescAllowedIPAddressesList   = "Allowed IP addresses list  \n"
	DescBackupRetentionPeriodDay = "Backup retention period (day) \n"
	DescBackupStartingTimeHour   = "Backup starting time (hour) \n"
	DescBackupStartingTimeMinute = "Backup starting time (minute) \n"
	DescClusterName              = "Cluster name \n"
	DescDBaaSEngineVersionID     = "DBaaS engine version ID \n"
	DescDatabaseEncoding         = "Database encoding \n"
	DescDatabaseLocale           = "Database locale \n"
	DescDatabaseName             = "Database name \n"
	DescDatabaseServicePort      = "Database service port \n"
	DescDatabaseUserName         = "Database user name \n"
	DescDatabaseUserPassword     = "Database user password \n"
	DescExample0000              = "  - example: '0000' \n"
	DescExample1                 = "  - example: 1  \n"
	DescExample104               = "  - example: 104 \n"
	DescExample12                = "  - example: 12 \n"
	DescExample2866              = "  - example: 2866 \n"
	DescExample60                = "  - example: 60 \n"
	DescExample7                 = "  - example: 7 \n"
	DescExampleACTIVE            = "  - example: 'ACTIVE' \n"
	DescExampleAsiaSeoul         = "  - example: 'Asia/Seoul' \n"
	DescExampleC                 = "  - example: 'C' \n"
	DescExampleDb1v1m2           = "  - example: 'db1v1m2' \n"
	DescExampleDb1v2m4           = "  - example: 'db1v2m4' \n"
	DescExampleFalse             = "  - example: False \n"
	DescExampleMON               = "  - example: 'MON' \n"
	DescExampleOS                = "  - example: 'OS' \n"
	DescExampleRunningStopped    = "  - example : 'RUNNING' (Create,Start) / 'STOPPED' (Stop) \n"
	DescExampleSSD               = "  - example: 'SSD' \n"
	DescExampleTest              = "  - example: 'test'  \n"
	DescExampleTest2             = "  - example: 'test' \n"
	DescExampleUTF8              = "  - example: 'UTF-8' \n"
	DescHAAvailability           = "HA availability \n"
	DescInstanceNamePrefix       = "Instance name prefix \n"
	DescMax23                    = "  - max: 23 \n"
	DescMax35                    = "  - max: 35 \n"
	DescMaxLength13              = "  - maxLength: 13  \n"
	DescMaxLength20              = "  - maxLength: 20  \n"
	DescMaxLength30              = "  - maxLength: 30  \n"
	DescMaxLength5120            = "  - maxLength: 5120  \n"
	DescMin00                    = "  - min: 00 \n"
	DescMin7                     = "  - min: 7 \n"
	DescMinLength16              = "  - minLength: 16  \n"
	DescMinLength2               = "  - minLength: 2  \n"
	DescMinLength3               = "  - minLength: 3  \n"
	DescMinLength8               = "  - minLength: 8  \n"
	DescNATAvailability          = "NAT availability \n"
	DescPatternActiveStandby     = "  - pattern: ACTIVE / STANDBY \n"
	DescPatternActiveStandbyHa   = "  - pattern: ACTIVE (HaEnabled=False) / ACTIVE_STANDBY (HaEnabled=True) \n"
	DescPatternAlpha             = "  - pattern: ^[a-zA-Z]*$ \n"
	DescPatternAlphaAlnum        = "  - pattern: ^[a-zA-Z][a-zA-Z0-9]*$ \n"
	DescPatternLowerAlnumDash    = "  - pattern: ^[a-z][a-zA-Z0-9\\-]*$ \n"
	DescPatternLowerAlpha        = "  - pattern: ^[a-z]*$ \n"
	DescPatternMinuteOptions     = "  - pattern: 5 / 10 / 30 / 60 \n"
	DescPatternPassword          = "  - pattern: ^(?=.*[a-zA-Z])(?=.*[`\\-[\\]~!@#$%^&*()_+={};:,<.>/?])(?=.*[0-9])(?=\\S*[^\\w\\s]).{8,30} (\"'제외) \n"
	DescPatternPasswordEng       = "  - pattern: ^(?=.*[a-zA-Z])(?=.*[`\\-[\\]~!@#$%^&*()_+={};:,<.>/?])(?=.*[0-9])(?=\\S*[^\\w\\s]).{8,30} (\"'exclude) \n"
	DescPeriodInHours            = "Period in hours \n"
	DescRoleType                 = "Role type \n"
	DescServerTypeName           = "Server type name \n"
	DescServiceState             = "Service state \n"
	DescSizeInGB                 = "Size in GB \n"
	DescStartingDayOfWeek        = "Starting day of week \n"
	DescStartingTime             = "Starting time \n"
	DescTimezone                 = "Timezone \n"
	DescUseMaintenanceOption     = "Use maintenance option \n"
	DescVolumeType               = "Volume type \n"
)

// RdbInstance(Group)RoleType이 REPLICA를 허용하는 서비스(mariadb, postgresql, epas)용 변형.
// 기존 상수는 REPLICA를 지원하지 않는 서비스가 계속 사용한다.
const (
	DescPatternActiveStandbyReplica   = "  - pattern: ACTIVE / STANDBY / REPLICA \n"
	DescPatternActiveStandbyHaReplica = "  - pattern: ACTIVE (HaEnabled=False) / ACTIVE_STANDBY (HaEnabled=True) / REPLICA \n"
)
